permalink: pretty
lsi: true
markdown: redcarpet

exclude: [Rakefile]
include: [atom.xml]
url: https://www.pragti.ch

author: Joris Pragt

git:
 source: source
 destination: master
 remote: origin

kramdown:
  input: GFM
  
plugins:
  - jekyll-gist
  
