permalink: pretty
lsi: true
markdown: kramdown
pygments: true
exclude: [Rakefile]
include: [atom.xml]
url: http://pragti.ch

author: Joris Pragt

git:
 source: source
 destination: master
 remote: origin
 
