permalink: pretty
lsi: true
markdown: redcarpet
highlighter: pygments
exclude: [Rakefile]
include: [atom.xml]
url: http://www.pragti.ch

author: Joris Pragt

git:
 source: source
 destination: master
 remote: origin

kramdown:
  input: GFM

gems:
  - jekyll-gist
